# Generated by Django 5.2.5 on 2025-08-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_backtestjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BacktestJob',
        ),
    ]
